### ISSUE TITLE
给新建集群增加备注说明

### ISSUE THREAD

**Issue by mike-pjj** [apolloconfig/apollo#5067]
**你的特性请求和某个问题有关吗？请描述**

清晰简洁地描述这个问题是什么。即，当碰到xxx时，总是感觉很麻烦
当集群太多了，多人使用时可能不知道创建名字代表意义。

**清晰简洁地描述一下你希望的解决方案**
增加备注，将备注显示在集群下方

**清晰简洁地描述一下这个特性的备选方案**

**其它背景**

在这里添加和这个特性请求有关的背景说明、截图
![image](https://github.com/apolloconfig/apollo/assets/37138377/2ef93c9b-9765-44d1-bd2c-9ffed442872c)

**Comment by nobodyiam** [comment]
This seems like an excellent idea. It would be possible for users to add comments to the clusters, similarly to how they can for the namespaces. Regarding the display aspect, a more effective approach might be to show these remarks when the mouse hovers over the cluster name, rather than just displaying them underneath the cluster name, which could become overly lengthy.
